### ISSUE TITLE
Bulk Texter Lite v2.1.4: Text failed. "fillNumberInput" failed.

### ISSUE THREAD

**Issue by setvalsantos** [Brismuth-Apps-LLC/bulk-texter-lite#236] opened 2023-12-15 18:11 UTC
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
It happened just today. Been using the extension for a while now. And I am reporting this on behalf of other users as well.

**Describe the bug**
"fillNumberInput" shows after Bulk Texter Lite fails to send texts to the list of numbers added to the recipients.
It seems to fail entering the number then it retries multiple times before the error.
Used both Firefox and Chrome (latest versions) and incognito/private browsing. Same issue.

**Screenshots**
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/142276714/548e5171-f607-4470-9294-a75fee309c2a)
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/142276714/9479d7c6-92cc-4d12-b044-13ce676e639a)
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/142276714/af3d9db0-7c0e-4db4-b212-fc4dc8f10fb6)
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/142276714/f3d48cf2-7382-45c1-bb6c-5f09ff491eb4)

**Comment by brismuth** [comment] 2023-12-15 21:24
After several hours of back and forth and video calls with Bulk Texter Pro subscribers, this issue is now resolved on Bulk Texter Pro:
https://www.bulktexterpro.com/

I will be working to port the changes to Bulk Texter Lite as well ASAP.

**Comment by setvalsantos** [comment] 2023-12-15 21:26
Thanks @brismuth.

**Comment by setvalsantos** [comment] 2023-12-18 15:59
Hi @brismuth, I know I shouldn't be asking this but do you have an ETA for the Bulk Texter Lite changes? Thanks.

**Comment by brismuth** [comment] 2023-12-18 18:15
Hi @setvalsantos, no worries.

I thought I had this issue completely resolved with Bulk Texter Pro, but it is not. Some users are still experiencing issues, so I'm focusing on that. Once I have the issue completely resolved in Bulk Texter Pro, I will port the fixes to Bulk Texter Lite. 

In the meantime, for anyone impacted by the Google Voice changes, I recommend trying the Bulk Texter Pro free 7 day trial and seeing if it resolves the issue. I'm hoping to have everything fixed by the time the trial would end, and anyone that doesn't want to pay for the Pro version can cancel it before it ends.

**Comment by AlxndrCtamn** [comment] 2023-12-18 22:02
Hi @brismuth i have a same issue with @setvalsantos . I am using Bulk Texter Lite, but it fails to send texts to the list of numbers added to the recipients. It seems to fail while entering the number, and then it retries multiple times before encountering an error.

![409392306_1346606049316877_6262618265025884523_n](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/112804072/3dfc0815-5501-4092-8ccd-475c741d1b9b)

**Comment by AlxndrCtamn** [comment] 2023-12-18 22:23
@brismuth then i try to bulk texter pro then the issue is same with bulk texter lite. 

![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/112804072/afca9565-fe80-489d-aa7c-8859b57bada5)

**Comment by brismuth** [comment] 2023-12-18 22:26
@AlxndrCtamn can you check which version of Bulk Texter Pro that is? v2.5.10 (released today) is not expected to have that issue (although some users are experiencing other issues still).

**Comment by AlxndrCtamn** [comment] 2023-12-18 22:28
This is a version of Bulk Texter Pro that we are using.

![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/112804072/472ce8bb-73f9-4074-959d-a5b99544948e)

**Comment by brismuth** [comment] 2023-12-18 22:31
For Bulk Texter Pro support (rather than Bulk Texter Lite), I recommend reaching out at support@bulktexterpro.com. We can troubleshoot further there.

**Comment by AlxndrCtamn** [comment] 2023-12-18 22:35
Okay, thank you. how about bulk texter lite? how to fix that issue?

**Comment by brismuth** [comment] 2023-12-18 22:36
See my message above in this thread:

https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/issues/236#issuecomment-1861242201

**Comment by AlxndrCtamn** [comment] 2023-12-18 22:46
Any other tips to fix that issue? Even if you don't subscribe to Bulk Texter Pro?

**Comment by AlxndrCtamn** [comment] 2023-12-19 16:55
Hi @brismuth any update for Bulk Texter lite?

**Comment by brismuth** [comment] 2023-12-19 17:01
I'm focused on fixing this in [Bulk Texter Pro](https://www.bulktexterpro.com/) first, which is 95% of the way there. Bulk Texter Pro now works as long as you are clicked into the Google Voice tab, but stops working when it's in the background, due to the changes Google made to Google Voice.

Once I have the fix completed for Bulk Texter Pro, I will be porting the fix to Bulk Texter Lite. I anticipate that being done in the next day or two.

**Comment by AlxndrCtamn** [comment] 2023-12-19 17:16
Thank you so much for update @brismuth

**Comment by setvalsantos** [comment] 2023-12-19 20:48
Hoping for the fix to be deployed ASAP 🙏  as we are using this daily.

**Comment by brismuth** [comment] 2023-12-19 21:59
The fix is now live in Bulk Texter Lite v3.0.2.

Please note that due to Google's recent changes, Google Voice does not currently support texting while in the background – you'll need to be clicked into the Google Voice tab for it to send.

v3.0.2 is released to the Firefox web store, and is still pending approval in the Edge web store.

You can follow the instructions here to update to the latest version manually:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/tree/main?tab=readme-ov-file#update-it

**Closed** 2023-12-19 21:59 UTC

**Comment by setvalsantos** [comment] 2023-12-19 23:17
Thanks, @brismuth! confirmed working on my end. One thing to note is the new zip for updating chrome does not have the src folder anymore.

**Comment by brismuth** [comment] 2023-12-19 23:32
Great catch @setvalsantos, I've updated the installation instructions to reflect that.

Thanks for the feedback! And thanks for your patience with the fix.

**Comment by AlxndrCtamn** [comment] 2023-12-19 23:40
Hi @brismuth, Just a quick note to express my appreciation for fixing BulkTexter Lite. Your speedy and effective solution saved the day. Thank you so much, but I am sad with this message :( "Google Voice does not currently support texting while in the background"

**Comment by brismuth** [comment] 2023-12-19 23:45
Yes, that is disappointing. 

I will continue looking into it and see if I can find a way to restore the background functionality. Again, the fix (if I can figure it out!) would come to Bulk Texter Pro first, and then Bulk Texter Lite.

**Comment by brismuth** [comment] 2023-12-20 19:20
@AlxndrCtamn @setvalsantos background sending functionality is restored in Bulk Texter Lite v3.0.3!

v3.0.3 is released to the Firefox web store, and is still pending approval in the Edge web store.

You can follow the instructions here to update to the latest version manually:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/tree/main?tab=readme-ov-file#update-it

**Comment by AlxndrCtamn** [comment] 2023-12-20 19:32
hi @brismuth is it okay with Google Chrome as well?

**Comment by brismuth** [comment] 2023-12-20 19:36
v3.0.3 is available for download via the link in the Readme that I shared above. 👍

**Comment by AlxndrCtamn** [comment] 2023-12-20 19:44
Thank you so much for fixing the Bulk Texter. @brismuth it's working on my end.

**Comment by setvalsantos** [comment] 2023-12-21 00:18
Confirmed working on my end as well. Thanks @brismuth

**Comment by shanannana** [comment] 2023-12-21 16:19
I do not see the updated version in the Chrome Store.  Is there any way else to update it for chrome?  The DOE blocks firefox.

![Chrome Store Sreenshot](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/154350494/2bfca0a0-ec7d-4cf8-8d1a-e3372c4362ad)

**Comment by brismuth** [comment] 2023-12-21 16:24
That is a screesnhot of the Edge store, which unfortunately takes around a week to review extension updates. Unfortunately Bulk Texter Lite is not currently available on the Chrome web store.

If you take a look at the installation instructions here, you'll see that there are instructions for installing Bulk Texter Lite manually on Chrome – maybe that would work for your situation?
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/tree/main?tab=readme-ov-file#installing-bulk-texter-lite

Alternatively, Bulk Texter Pro is currently up to date on the Chrome web store, and offers a free 7 day trial, so that could probably get you through until the Edge store listing for Bulk Texter Lite is updated.
https://chromewebstore.google.com/detail/bulk-texter-pro/kpjadjgajlgmkefnnihfedmcabapnndj

**Comment by KingdomLaz** [comment] 2023-12-22 15:11
@brismuth I've tried to update my Chrome but it never finishes reloading.  Could it be because my Chrome is Version 103.0.5060.132 which stopped receiving updates June, 2022?  If so, is there a work around for an old Chromebook?  Will Bulk Texter work on an iPad Air?  Will it work on an iPhone?

Thank you.

**Comment by brismuth** [comment] 2023-12-22 17:44
@KingdomLaz please file a new issue, as that sounds unrelated to this one. 

In the new issue, can you clarify what the issue is that you're seeing? Where does it not finish reloading? A screenshot might help. Thanks.

**Comment by Geremia** [comment] 2024-03-14 21:25
@brismuth  I get this issue in v3.0.8.
