### ISSUE TITLE
Integrate with Google Sheets / CSVs

### ISSUE THREAD

**Issue by EdWood110** [Brismuth-Apps-LLC/bulk-texter-lite#58] opened 2019-04-05 18:52 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Here is another idea for your amazing tool, would it be possible to feed the Bulk Texter via a Google sheet instead of manual copy and paste name and number into the app? Could there be a way to also receive messages and a add this info onto another Google sheet as well? But the most important part, I think, would be to feed the Texter via Sheet... so we can automate it even further.
**Describe alternatives you've considered**

**Additional context**
Thank you for this easy to use app, it saved us already a lot of time.

**Comment by brismuth** [comment] 2019-04-05 18:59
That's more work than I'm willing to implement, but I'm happy to consider pull requests.

**Comment by 877693665** [comment] 2019-04-18 00:49
Hi，I have a functional suggestion, which is the time interval.

Thank you very much for the software. It's wonderful.I think it's probably limited by some policies of gogole voice. If you can add a time interval, I think it's great. It will become a better tool.

**Comment by brismuth** [comment] 2019-04-22 23:53
@877693665 that isn't really relevant to the issue you've commented on. It is, however, a duplicate of the second feature request on issue #54.

**Comment by brismuth** [comment] 2021-06-30 03:20
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/58

**Comment by CNBarnes** [comment] 2021-09-02 15:39
I was just about to make this same suggestion (integrate with Google sheets).  I already have a simple spreadsheet that I use - it's just 2 columns:  column A is the phone number, Colum B is the name. 

(actually, Column A is the phone number, with a comma after it.  eg.  "123-456-7890, "

Right now I have to copy the entire range, then paste into GVBT.  It's not a huge step, but it does sometimes create a step for human error.  Being able to simply have GVBT point to a spreadsheet would avoid that.


Also, I just made stand-alone suggestion that you add Venmo as a way to fund requests..  :-D

**Comment by brismuth** [comment] 2022-11-03 14:28
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. I'd love if you could check it out and drop any feedback you have here.

**Closed** 2023-01-11 08:06 UTC
Labels: enhancement
